---
before_script:
  - "npm install -g grunt-cli && mysql -e 'create database myapp_test'"
env:
  - "PORT=3000 APP_HOSTNAME=\"http://localhost:3000\" DB_USERNAME=\"travis\" DB_PASSWORD=\"\" DB_DATABASE=\"myapp_test\" DBOPTIONS_DIALECT=\"mysql\" DBOPTIONS_LOGGING=false SESSION_SECRET=\"secret\" ALLOWED_USERS=\"travis:travis\" ALLOWED_DOMAINS=\"http://localhost:3001 http://localhost:3002\" LOGINAPI=\"http://travis:travis@localhost:3000\" SUPPORTED_LANGS='[\"en-US\"]'"
language: node_js
node_js:
  - "0.8"
  - "0.10"
